//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaMoneda
    {
        public int IdEmpresaMoneda { get; set; }
        public Nullable<double> Cambio { get; set; }
        public int Activo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdEmpresa { get; set; }
        public int IdMonedaPrincipal { get; set; }
        public Nullable<int> IdMonedaAlternativa { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Moneda Moneda1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
