//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Articulo = new HashSet<Articulo>();
            this.Categoria = new HashSet<Categoria>();
            this.Comprobante = new HashSet<Comprobante>();
            this.Cuenta = new HashSet<Cuenta>();
            this.EmpresaMoneda = new HashSet<EmpresaMoneda>();
            this.Gestion = new HashSet<Gestion>();
            this.Nota = new HashSet<Nota>();
        }
    
        public int IdEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Nit { get; set; }
        public string Sigla { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public int Niveles { get; set; }
        public int IdUsuario { get; set; }
        public int estado { get; set; }
        public Nullable<bool> Integracion { get; set; }
        public Nullable<int> IdCuentaCaja { get; set; }
        public Nullable<int> IdCuentaCreditoFiscal { get; set; }
        public Nullable<int> IdCuentaDebitoFiscal { get; set; }
        public Nullable<int> IdCuentaCompras { get; set; }
        public Nullable<int> IdCuentaVentas { get; set; }
        public Nullable<int> IdCuentaIt { get; set; }
        public Nullable<int> IdCuentaItPorPagar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria> Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobante> Comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuenta> Cuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaMoneda> EmpresaMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestion> Gestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Nota { get; set; }
        public virtual Cuenta Cuenta1 { get; set; }
        public virtual Cuenta Cuenta2 { get; set; }
        public virtual Cuenta Cuenta3 { get; set; }
        public virtual Cuenta Cuenta4 { get; set; }
        public virtual Cuenta Cuenta5 { get; set; }
        public virtual Cuenta Cuenta6 { get; set; }
        public virtual Cuenta Cuenta7 { get; set; }
    }
}
