//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public int IdPeriodo { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fechainicio { get; set; }
        public System.DateTime Fechafin { get; set; }
        public int Estado { get; set; }
        public int IdUsuario { get; set; }
        public int IdGestion { get; set; }
    
        public virtual Gestion Gestion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
